trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables: 
  buildConfiguration: 'Release'

steps:

- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'

- script: docker network create internet && docker run -d -p 27017-27019:27017-27019 --net=internet --name database_mongo_stone mongo:latest
  displayName: Build Mongo Container

- script: docker build --file ./WebApiStone/WebApiStone.Tests/WebApiStone.Test.Dockerfile --tag webapistone.test ./WebApiStone.Tests
  displayName: Build Test Container Api

- script: docker run --net=internet webapistone.test
  displayName: Test Api Container

- script: docker build -f ./WebApiStone/WebApiStone/Dockerfile --build-arg prod="prod" ./WebApiStone
  displayName: Build Container API

- script: npm install --prefix ./WebAppStone && npm run build 
  displayName: Build Frontend