version: "3.7"

services:
  database:
    image : mongo
    container_name: database_mongo_stone
    environment:
    - PUID=1000
    - PGID=1000
    ports:
    - 27017:27017

  api:
    container_name: web_api_stone
    depends_on:
      - database
    build:
      context: ./WebApiStone
      dockerfile: ./WebApiStone/Dockerfile
    ports:
      - 5000:80

  app:
    container_name: web_app_stone
    depends_on:
      - api
    build:
      context: ./WebAppStone/
      dockerfile: ./Dockerfile
    ports:
      - 9000:80
      
volumes:
  mongo_data:
