version: "3.7"

services:
  database:
    image : mongo
    container_name: database_mongo_stone
    environment:
    - PUID=1000
    - PGID=1000
    ports:
    - 27017:27017
    volumes:
      - mongo_data:/data/db
    networks: 
      - internet

  api:
    container_name: web_api_stone
    depends_on:
      - database
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - "DatabaseSettings:ConnectionString=mongodb://database_mongo_stone:27017"
     - "DatabaseSettings:DatabaseName=StoneDatabase"
     - "DatabaseSettings:CollectionName=DemographicCensus"
    build:
      context: ./WebApiStone
      dockerfile: ./WebApiStone/Dockerfile
    ports:
      - 5000:80
    restart: always
    networks: 
      - internet

  app:
    container_name: web_app_stone
    build:
      context: ./WebAppStone/
      dockerfile: ./Dockerfile
    ports:
      - 9000:80
    restart: always
    networks: 
      - internet
      
volumes:
  mongo_data:

networks:
  internet:
    name: stone
