name: Build API

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test: 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Mongo Container
      run: docker network create internet && docker run -d -p 27017-27019:27017-27019 --net=internet --name database_mongo_stone mongo:latest
    
    - name: Build Test Container Api
      run: docker build --file ./WebApiStone/WebApiStone.Test.Dockerfile --tag webapistone.test ./WebApiStone
      
    - name: Test Api Container
      run: docker run --net=internet webapistone.test

  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Build Container API
      run: docker build -f ./WebApiStone/WebApiStone/Dockerfile --build-arg prod="prod" ./WebApiStone
